apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: commande
spec:
  host: microservice1.mcom.svc.cluster.local
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1
    outlierDetection:
      consecutiveErrors: 5
      interval: 5s
